version: '3.8'

services:
  rest-service:
    build: ./rest-service
    container_name: rest-service
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BROKER}"
      EVENT_SERVICE_URL: "http://event-service:8001"
      CACHE_SERVICE_URL: "http://cache-service:8002"
    ports:
      - "${PORT}:${PORT}"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${PORT}"]

  event-service:
    build: ./event-service
    container_name: event-service
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BROKER}"
      DATABASE_URL: "${DATABASE_URL}"
    ports:
      - "8001:8001"

  cache-service:
    build: ./cache-service
    container_name: cache-service
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BROKER}"
      REDIS_URL: "${REDIS_URL}"
    ports:
      - "8002:8002"
